-- ============================================================
-- V1: Esquema base de inventario (PostgreSQL) - desde JPA (validate)
-- Incluye CHECKs de enums e IDENTITY tal como los genera Hibernate.
-- ============================================================

CREATE TABLE inventario (
    cantidad_disponible integer NOT NULL,
    costo_unitario numeric(10,2),
    fecha_fabricacion date,
    fecha_vencimiento date NOT NULL,
    iva numeric(5,2),
    moneda character varying(3),
    precio_unitario numeric(10,2) NOT NULL,
    requiere_receta boolean NOT NULL,
    stock_maximo integer,
    stock_minimo integer NOT NULL,
    actualizado_en timestamp(6) without time zone,
    categoria_id bigint,
    creado_en timestamp(6) without time zone,
    id bigint NOT NULL,
    proveedor_id bigint,
    estado character varying(20),
    codigo_producto character varying(50) NOT NULL,
    lote character varying(50),
    actualizado_por character varying(100),
    concentracion character varying(100),
    creado_por character varying(100),
    presentacion character varying(100) NOT NULL,
    ubicacion character varying(100),
    laboratorio character varying(200),
    nombre character varying(200) NOT NULL,
    categoria character varying(255),
    descripcion text,
    CONSTRAINT inventario_cantidad_disponible_check CHECK ((cantidad_disponible >= 0)),
    CONSTRAINT inventario_categoria_check CHECK (((categoria)::text = ANY ((ARRAY['ANALGESICO'::character varying, 'ANTIBIOTICO'::character varying, 'ANTIINFLAMATORIO'::character varying, 'ANTIHISTAMINICO'::character varying, 'CARDIOVASCULAR'::character varying, 'OTROS'::character varying])::text[]))),
    CONSTRAINT inventario_estado_check CHECK (((estado)::text = ANY ((ARRAY['ACTIVO'::character varying, 'AGOTADO'::character varying, 'CADUCADO'::character varying, 'DISCONTINUADO'::character varying, 'EN_ESPERA'::character varying])::text[]))),
    CONSTRAINT inventario_moneda_check CHECK (((moneda)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT inventario_stock_minimo_check CHECK ((stock_minimo >= 0))
);
ALTER TABLE inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE movimientos_inventario (
    cantidad integer NOT NULL,
    fecha_movimiento timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    producto_id bigint NOT NULL,
    tipo_movimiento character varying(20) NOT NULL,
    usuario character varying(100),
    motivo character varying(255),
    observaciones text,
    CONSTRAINT movimientos_inventario_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SALIDA'::character varying, 'AJUSTE'::character varying, 'DEVOLUCION'::character varying])::text[])))
);
ALTER TABLE movimientos_inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME movimientos_inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY inventario
    ADD CONSTRAINT inventario_codigo_producto_key UNIQUE (codigo_producto);
ALTER TABLE ONLY inventario
    ADD CONSTRAINT inventario_pkey PRIMARY KEY (id);
ALTER TABLE ONLY movimientos_inventario
    ADD CONSTRAINT movimientos_inventario_pkey PRIMARY KEY (id);
CREATE INDEX idx_codigo_producto ON inventario USING btree (codigo_producto);
CREATE INDEX idx_estado ON inventario USING btree (estado);
CREATE INDEX idx_fecha_vencimiento ON inventario USING btree (fecha_vencimiento);
