spring:
  application:
    name: recepcion-service
  datasource:
    url: jdbc:postgresql://localhost:5433/recepcion_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8001

logging:
  level:
    com.recepcion: DEBUG
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    # Si Eureka no esta levantado, no impide el arranque del servicio.
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true