server:
  port: 8173
spring:
  application:
    name: historia-clinica-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update
    show-sql: true
    hibernate:
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/historial_medico_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
