server:
  port: 8002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sihce_citas
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    com.citas: DEBUG
    org.springframework.cloud.openfeign: DEBUG
